### ISSUE TITLE
Failed with 'DuckDuckGo' and 'Google' search engines

### ISSUE THREAD

**Issue by webmastak** [WindSoilder/hors#102]
`Search stackoverflow link failed with 'DuckDuckGo' search engine, you can try another engine through `-e` argument, or specify `$HORS_ENGINE` env variable to another value`

`Search stackoverflow link failed with 'Google' search engine, you can try another engine through `-e` argument, or specify `$HORS_ENGINE` env variable to another value`

Google does not work through a proxy either.
DuckDuckGo does not always work through a proxy.
Only Bing it works through and without a proxy.

**Comment by WindSoilder** [comment]
Oh my god, thanks for your report.  I'm using Bing engine in my daily work, so I don't detect this issue.

I will try to fix it this week :-)

**Comment by WindSoilder** [comment]
Hi, thanks for your report.

I have tried to fix it and release a new version 0.8.1, would you please try this?

> DuckDuckGo does not always work through a proxy.
For the duckduckgo engine, it's occational issued by `duckduckgo` search engine it self, sorry for that I don't know how to fix this for now, if you can't work with duckduckgo engine, please try another :-)

**Comment by webmastak** [comment]
Yes I tried version 0.8.1. 
Google search engine works.
But for some reason the history file is not written ` ~/.cache/hors/answers`

**Comment by WindSoilder** [comment]
> I figured out when deleting the hors directory, it doesn't get created. If you create it by hand, then history is written.
It would be nice to fix it.

I have created another issue to handle this problem :-)

> Why not search directly on stackoverflow.com/search?q=sed ?

I find out that for searching stackoverflow, it's better to use [Stack Exchange API](https://api.stackexchange.com/docs), and for this case, you can try `-e stackoverflow` argument :-)

**Comment by webmastak** [comment]
Yes I tried -e stackoverflow, works good.
