### ISSUE TITLE
Provide binaries (via GitHub actions)

### ISSUE THREAD

**Issue by dufferzafar** [WindSoilder/hors#48]
Hi, you could setup a GitHub Workflow to automatically release new tags.

This would allow people to just download the binaries and not have to worry about compiling it themselves.

For reference:

Ripgrep's workflow: https://github.com/BurntSushi/ripgrep/blob/master/.github/workflows/release.yml

GitUI's workflow: https://github.com/extrawurst/gitui/blob/master/.github/workflows/cd.yml

**Comment by WindSoilder** [comment]
@dufferzafar Thank you!  I will try to dive into it and figure out how to deal with this.

**Comment by keng42** [comment]
@WindSoilder  need a pr? 

https://github.com/keng42/hors/commit/c923d6

**Comment by WindSoilder** [comment]
@keng42 yes please

**Comment by 06kellyjac** [comment]
resolved by #54

**Comment by WindSoilder** [comment]
Thanks to #54, I have tried to release a version [v0.6.3](https://github.com/WindSoilder/hors/releases/tag/v0.6.3).  With nothing changes, just update some dependencies. 

And it provides binaries successfully.  That's a great work, thanks @keng42 !
