### ISSUE TITLE
程序不能正常使用

### ISSUE THREAD

**Issue by Lmina0524** [WindSoilder/hors#5]
系统：windows 10
版本：hors 0.3.3
问题描述：在测试例子' hors“pandas dataframe to csv"'时报错，报错信息：

Error: HorsError { repr: Network(Error(Io(Custom { kind: TimedOut, error: StringError("timed out") }), "https://www.bing.com/search?q=site:stackoverflow.com%20pandas%20dataframe%20to%20csv")) }

已确认在连网情况在操作，并且可在浏览器中打开报错信息中的网址。

如图所示：
![image](https://user-images.githubusercontent.com/52343808/60381152-aec3bc00-9a82-11e9-96c2-31202772d22e.png)

**Comment by WindSoilder** [comment]
看起来是通过https协议访问的时候出了问题, hors后面会处理一下.

优先通过https发送请求, 如果失败的话, 会通过http协议发送请求.

**Comment by WindSoilder** [comment]
0.4.0版本已经发布, 上述问题应该可以更好的解决
