### ISSUE TITLE
Accept multiple query arguments and join with spaces

### ISSUE THREAD

**Issue by casey** [WindSoilder/hors#62]
Since hors currently accepts a single query argument, multi-word queries must be quoted.

A possible way to avoid requiring quoting, in the absence of special characters, would be to accept multiple arguments, and join them with spaces to form the query.

So running `hors how do i rust` would result in the query `how do i rust`.

A possible downside of doing this is that it wouldn't allow introducing additional positional arguments in the future. So, for example, it wouldn't be possible to introduce an optional positional argument for the engine, like `horse 'how do i rust' bing`.

**Comment by WindSoilder** [comment]
@casey Thanks for your suggestion, I love the idea, it makes the program easiler to use.

Take just one positional argument is fine to me.

**Comment by dzervas** [comment]
I had the exact same thought :joy:
PR submitted #63

**Comment by dzervas** [comment]
Lol, fastest feature request & implementation ever! #63 merged, lets close this :muscle:

**Comment by WindSoilder** [comment]
The PR have merged :-)  Thanks very much.

**Comment by casey** [comment]
Nice!
