### ISSUE TITLE
Special formatting characters rendered as text in Windows Powershell and CMD

### ISSUE THREAD

**Issue by FuSoftware** [WindSoilder/hors#68]
OS : Windows 10 using `cmd.exe` and `powershell`

Upon trying your tool, it seems like the character encoding used to, I guess, color the lines, or at least add some text encoding, produces strange characters when used on Powershell and Windows CMD.

I suppose these are the special chracters used for the color formatting. I'm curious if it's possible, in the source code, to do automatic terminal detections to disable them when not on a compatible terminal.

And yes, I know about the `-r` option, which I use, it's just that a Windows user not being aware of it might be surprised

```
hors "dart print text"
- Answer from https://stackoverflow.com/questions/21028751/how-do-i-print-to-the-console-with-dart
[38;2;211;208;200mimport 'dart:html';
[38;2;211;208;200m
[38;2;211;208;200mmain() {
[38;2;211;208;200m  var value = querySelector('input').value;
[38;2;211;208;200m  print('The value of the input is: $value');
[38;2;211;208;200m}
```

**Comment by WindSoilder** [comment]
Oh, hi.  Very thanks for your report.

I'm sorry that I haven't make fully tests on `powershell` and `cmd`(due to the lacks of PC).

I will try to figure out how to deal with this in a better way :)  There are 2 ways to handle this:

1. fix the issue, make colorful output in `powershell` and `CMD`, or
2. If I can hardly find a solution to colorize output in `powershell` and `CMD`, we can output the `raw` text by default on windows system as a temporary solution.  (don't need to specify `-r` argument everytime).

**Comment by dzervas** [comment]
I dunno if we can use a custom crate to colorize but this crate does that well: https://github.com/BurntSushi/termcolor

**Comment by FuSoftware** [comment]
I'll take a look this week, since I have both PS and CMD at hand. For now there's always the `-r` option, so it's not a big issue. But since I saw the `so` crate supports PS color formatting, I'm sure there's a way

**Comment by WindSoilder** [comment]
@FuSoftware You can try to make use of [windows terminal](https://github.com/microsoft/terminal) which support colorize feature.

For `powershell` and `cmd`, I need to check for a while :-)

**Comment by WindSoilder** [comment]
Hi, Windows Powershell and CMD should be ok for now :-) Feel free to have a look.
![图片](https://user-images.githubusercontent.com/22256154/90331457-0e628b00-dfe7-11ea-8a02-e0b3f49e380a.png)

And please note that `hors` can't highlight `dart` lang, so the output will be the same as `hors dart print text -r`
