### ISSUE TITLE
Unreadable colors

### ISSUE THREAD

**Issue by aleksator** [WindSoilder/hors#71]
I have a problem with default coloring scheme. It contains both white and dark gray colored words, so half of it is very hard to read with whitish background theme, while another half with dark background theme (see screenshot).
![hors_colors](https://user-images.githubusercontent.com/2221354/89706529-36127d00-d96f-11ea-8fde-50a4e0a7ebfa.png)

Hors version is 0.6.4, run under KDE, Yakuake, Sweet console theme.
I tried other themes and it was still problematic.

**Comment by dzervas** [comment]
This will be solved with #61 I think, where the color scheme will be configurable.

Apart from that though, I think that you've changed the default colors (terminal themes tend to do that), so for example red could appear as blue. To fix that, I think the best solution is to use more "safe" colors as default, so that it appears "good enough" on most terminal themes. We can read how `highlight` or https://github.com/sharkdp/bat do things and how they picked colors.

**Comment by aleksator** [comment]
I don't think the issue is the current theme that I am using, as I noted I tried different ones.
Here's the example with default KDE terminal theme Breeze (I changed global KDE theme to default Breeze Dark as well just in case):

![hors_colors_breeze](https://user-images.githubusercontent.com/2221354/89713839-08dfc200-d9a3-11ea-8163-b24cb9f211d8.png)
With terminal theme set to "White on Black":
![hors_colors_black_and_white](https://user-images.githubusercontent.com/2221354/89713917-a1764200-d9a3-11ea-9fd5-f081056db8d1.png)

In fact, hors output colors don't change with the theme at all as far as I noticed, only the colors of the text I typed and the background change.

**Comment by dzervas** [comment]
Oh, I hear you...
![image](https://user-images.githubusercontent.com/1029195/89715130-64fb1400-d9ac-11ea-93d4-5bbe45434eb2.png)

**Comment by WindSoilder** [comment]
Hi, thanks for your report, I can reproduce this issue too.

It seems that `hors` does not take the most approprate tag to colorize output.  For this link, it just take `json` scheme to colorize....

Maybe I need to take a little time to think how to fix it appropriately.

**Comment by WindSoilder** [comment]
Oh, maybe there is a better way to select language scheme to colorize code.
<img width="436" alt="图片" src="https://user-images.githubusercontent.com/22256154/89745919-4e0e0c00-dae9-11ea-942a-dda2fdf94540.png">
I can make use of this attribute :-)

**Comment by dzervas** [comment]
oh ok, if it's a problem on that specific answer (marked as java while it's Rust) I don't consider it a bug

**Comment by WindSoilder** [comment]
@aleksator Hi, I have publish a new version(0.6.6) to handle this, feel free to check it out :-)

**Comment by aleksator** [comment]
@WindSoilder Looks great! Thank you.
