### ISSUE TITLE
Why don't we use SO's search?

### ISSUE THREAD

**Issue by dzervas** [WindSoilder/hors#74]
I know that this question is kinda stupid, but why don't we use SO's search? Search accuracy is bad? @WindSoilder

**Comment by WindSoilder** [comment]
Hmm... In the beginning, this project is just a copy of [howdoi](https://github.com/gleitz/howdoi) project, so I do what it do.

Personally I think search engine may give me better result about SO link.  I have investgated (so)[https://github.com/samtay/so] project, maybe we can try to support SO's search, and see what it happens :)

**Comment by WindSoilder** [comment]
Investigation result:
[so](https://github.com/samtay/so) is make use of [Stack Exchange API](https://api.stackexchange.com/docs), but I think it may needs more setup.

I can try to make use of so search link: https://stackoverflow.com/search?q=rust serde example.  It may make the implementation easiler.

**Comment by dzervas** [comment]
so we need to write a client huh? Good task for a milestone (version 1.0?)

**Comment by WindSoilder** [comment]
For now so's search is supported :-)
