### ISSUE TITLE
A bit of info on `lang-` class

### ISSUE THREAD

**Issue by dzervas** [WindSoilder/hors#75]
I found a question with multiple answers: https://stackoverflow.com/questions/45015/safely-turning-a-json-string-into-an-object

Here there are `<pre><code>` both empty and with the `lang-` class in the html document (before JS rendering).

The second answer (answer-3627901), does not have a lang class:
![image](https://user-images.githubusercontent.com/1029195/90001264-e5b25c80-dc99-11ea-83c0-c26800bdba55.png)
![image](https://user-images.githubusercontent.com/1029195/90002268-1d6dd400-dc9b-11ea-8482-a4f0e7c352b4.png)

While an answer further down (answer-51907405) has it - but it's a snippet:
![image](https://user-images.githubusercontent.com/1029195/90001603-4b9ee400-dc9a-11ea-92a9-87693c1ef8f9.png)
![image](https://user-images.githubusercontent.com/1029195/90001681-68d3b280-dc9a-11ea-8e9e-69ccb9379681.png)

And the last answer (answer-59526105) has it but it's not a snippet:
![image](https://user-images.githubusercontent.com/1029195/90001838-9882ba80-dc9a-11ea-9329-5518cbab95c9.png)
![image](https://user-images.githubusercontent.com/1029195/90001896-a59fa980-dc9a-11ea-9be4-69f640c49e79.png)

This concludes it. I THINK that if in the answer you post you put the language in the code fence (like ```` ```Rust... ````) it gets the class by the server. If not the client JS guesses the syntax

I think the best way to go on syntax guessing is to check for the class and then do the tag-rating system.

**Comment by WindSoilder** [comment]
@dzervas Excellent!  I'm very appreciate for your investigation, I think we can repoen the PR #72 .
