### ISSUE TITLE
[From reddit suggestion] available by other than cargo.

### ISSUE THREAD

**Issue by WindSoilder** [WindSoilder/hors#76]
Provide installation from homebrew(on mac), apt(on linux), maybe others(Chocolatey on windows)

**Comment by dzervas** [comment]
Packaging is a pain - first of all we need to package in the various formats and then we'll see how we make it to an official repo (debian/fedora/ubuntu/etc.). A milestone for a packaging action on every release should get in place

**Comment by WindSoilder** [comment]
Yeah, like the CI provide binary package per release, it's better to auto-upload the binary to these platform

**Comment by WindSoilder** [comment]
Hmm... It's too complicated for me, for now I just add support for `brew` and `scoop`

**Comment by WindSoilder** [comment]
Close this for now, for more auto-packaging action move to #93
