### ISSUE TITLE
Duck Duck Go seems to have parse issues on macOS at least

### ISSUE THREAD

**Issue by monkeydom** [WindSoilder/hors#81]
seems to fail pretty hard in my environment, any way to give you more good data?

```bash
dom@darthdom:~$ hors c# literal array
- Answer from https://stackoverflow.com/questions/4894120/what-does-for-mean
while(true)
dom@darthdom:~$ hors csharp literal array
Search for target link failed: Parse("Can\'t find search result...")
```

```
$> hors -V
hors 0.6.8
```

**Comment by monkeydom** [comment]
update: seems to be a serach engine issue, works fine with -egoogle.

**Comment by WindSoilder** [comment]
Hi, thanks for your report.  

It seems that duckduckgo engine sometimes doesn't work.  You can also use `HORS_ENGINE` environment variable.

**Comment by monkeydom** [comment]
If this is a kown issue it would probably be best to improve the error message to reflect this, or have a fallback search enginge as default.

**Comment by WindSoilder** [comment]
> If this is a kown issue it would probably be best to improve the error message to reflect this

Agree with this :-)

**Comment by WindSoilder** [comment]
<img width="749" alt="图片" src="https://user-images.githubusercontent.com/22256154/91109650-379dae00-e6ae-11ea-95b2-47069befad1f.png">
Oh, I see what happened to duckduckgo search engine, it seems that ddg engine may return some message like this, and we have no way to fix it for now.
