### ISSUE TITLE
Add clear cache

### ISSUE THREAD

**Issue by webmastak** [WindSoilder/hors#98]
Add function to clear cache as in howdoi.

I decided by adding to my **.zshrc** : `alias hr=' rm -rf ~/.cache/hors/* &>/dev/null'`

**Comment by WindSoilder** [comment]
Hi, thanks for your suggestion.  I think it's useful to add a subcommand to handle this :-)  
Or make a option (like `--clear-cache` in howdoi).  

This will be finish with the next version :-)

**Comment by WindSoilder** [comment]
Hi, for now v0.7.2 is release, you can use `--clear-cache` flag to clear local cache.  It's solved on #100
